- name: Copy systemd service files
  template:
      src: "files/{{ item }}.service"
      dest: "/etc/systemd/system/{{ item }}.service"
  with_items:
      - rover-onboard-auton-light
      - rover-onboard-cv
      - rover-onboard-filter
      - rover-onboard-kinematics
      - rover-onboard-microscope
      - rover-onboard-nav
      - rover-onboard-odrive-bridge@
      - rover-onboard-raman
      - rover-onboard-science-controls
      - rover-onboard-sensor-package
      - rover-onboard-teleop

- name: Copy environment variable definitions 
  copy:
      src: files/rover.env
      dest: /etc/default/rover.env

- name: Install udev rules
  copy:
      src: files/rover.rules
      dest: /etc/udev/rules.d/10-rover.rules

- name: Reload systemd
  systemd: daemon_reload=yes

- name: Enable services
  systemd: name={{item}} enabled=yes
  with_items:
      - rover-onboard-auton-light.service
      - rover-onboard-cv.service
      - rover-onboard-filter.service
      - rover-onboard-kinematics.service
      - rover-onboard-microscope.service
      - rover-onboard-nav.service
      - rover-onboard-odrive-bridge@FRONT_MOTORS.service
      - rover-onboard-odrive-bridge@BACK_MOTORS.service
      - rover-onboard-raman.service
      - rover-onboard-science-controls.service
      - rover-onboard-sensor-package.service
      - rover-onboard-teleop.service
