- name: Create desktop file
  template:
    src: files/MRover_UI.desktop
    dest: /usr/share/applications/MRover_UI.desktop
    mode: 0755

- name: Copy systemd service and timer files
  template:
    src: "files/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - rover-base_station_gui.service
    - rover-base_station_gstreamer@.service
    - rover-lcm_bridge_server.service
    - rover-base_station_kineval.service
    - rover-base_station_gstreamer@.timer

- name: Copy environment variable definitions
  copy:
    src: files/rover.env
    dest: /etc/default/rover.env

- name: Reload systemd
  systemd: daemon_reload=yes

- name: Enable services and timers
  systemd: name={{item}} enabled=yes
  with_items:
    - rover-base_station_gui.service
    - rover-base_station_gstreamer@5000.service
    - rover-base_station_gstreamer@5001.service
    - rover-base_station_gstreamer@5002.service
    - rover-lcm_bridge_server.service
    - rover-base_station_kineval.service
    - rover-base_station_gstreamer@5000.timer
    - rover-base_station_gstreamer@5001.timer
    - rover-base_station_gstreamer@5002.timer