- name: Install udev rules for ST-Link V2.1
  copy:
      src: files/49-stlink-v21.rules
      dest: /etc/udev/rules.d/49-stlink-v21.rules

- name: Force udev to reload rules
  shell: udevadm control --reload-rules
