---
- hosts: all
  become: yes
  gather_facts: False
  vars:
      ubuntu_release: xenial
      running_user: nvidia
      workspace_dir: /home/ubuntu/mrover-workspace
  roles:
  - onboard_dev
  - onboard_networks
  - onboard_services
