- name: Set up NodeSource signing key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Set up NodeSource repository for Node 10.x
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_10.x {{ ubuntu_release }} main"
    state: present

- name: Set up Yarn signing key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Set up Yarn repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present

- name: Install developer packages
  apt: 
    name:
      - nodejs
      - yarn
      - gstreamer1.0-tools
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - python-gi
      - python-gi-cairo
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - python3-venv
      - python3-wheel
      - python3-dev
      - libgirepository1.0-dev
      - build-essential
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - zlib1g-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libcairo2-dev
    state: present
