- name: Install developer packages
  apt: 
    name:
      - python-gi
      - python-gi-cairo
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - python3-venv
      - python3-wheel
      - python3-dev
      - libgirepository1.0-dev
      - build-essential
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - zlib1g-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libcairo2-dev
      - autoconf
      - libtool
      - libglib2.0-dev
      - libpython3.6-dev
      - virtualenv
      - git
      - python3-gst-1.0
      - gstreamer1.0-tools
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
    state: present
